server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: wushunyu
    driver-class-name: com.mysql.cj.jdbc.Driver
